# Generated by Django 5.0.6 on 2024-08-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
