# What include in this file:
# The Django Admin feature, Easy & Powerful Data Administration

# Simply again we use here last-day all files.  
# Now goto url's.py file in the main sub folder and see "admin/" path there.
# Run your server.
# 
#  write in url or goto admin path where you see one administration form there.


# Now for login you need to create a "superuser" in your Django.
# for that write code in terminal:
# python manage.py createsuperuser
# 
# then enter name (here entered: krish)
# then enter email address (here entered: abc@gmail.com)
# then enter password  (here entered: abc123)
# then re-enter your password   (Remember you can not see your writen password but it still writen)
# and you will see: Superuser created successfully.


# Now run again server and login at administration.
# overlook what are there. 
# Now goto models.py file 
# see there how to add in admin area Book class now you need to click on add new book.
# For your info. we goto add new book section and fill all field except slug and click on save button but it refuse to save it because field is not to be empty if we write any word which we think and click on save button then it will save it.
# Now if you again open that new book and you see slug is overrite because over auto generate slug overrite it which we create at models.py file. 


# Now goto models.py file where in slug field we add the blank=True
# from now if you not enter slug field at Django Administration it will ok.

# Now we add editable=False so user can't see this field and over autogenerated slug take place there.  

# now goto admin.py file where we add new class.
# To know about more in Django Admin area goto official Docs: https://docs.djangoproject.com/en/5.0/ref/contrib/admin/
